### PR TITLE
Removing views from scala code.

### PR DESCRIPTION
**Pull request by DarkDimius**
Scala views don't interop with parallel collections well,
constructions like col.par.view and col.view.par are known to be broken.
Moreover none of functionality of views is used in those benchmarks,
so usage of views seems unnecessary.

### CODE REVIEW

**Comment by biboudis** [comment]
@DarkDimius Thanks for your interest and for taking the time to send a PR. 

Our goal is to measure streaming APIs and in order to avoid producing intermediate results we should use the corresponding combinators/data structures of each language. I believe .view is the appropriate abstraction, and in order to be as objective as possible, we should keep that.

**Comment by biboudis** [comment]
We have run the Scala tests on Linux, on the same machine, with your changeset. We believe that views is the appropriate abstraction in the scope of the paper, but we wanted to see the performance with your recommendation as well. 

The parallel tests were improved but not substantially (sumOfSquaresPar crashed due to exceeding the GC limit). The sequential tests suffered a little bit.

screenshot from 2014-06-20 19 10 43

screenshot from 2014-06-20 19 11 10

**Comment by shipilev** [comment]
Well, you seem to be running in a constrained heap. Unlock -Xmx -Xms, maybe?

**Comment by biboudis** [comment]
Hi @shipilev!! Yes, sure!

I've run @DarkDimius 's changeset again, this time with 3GB of exact heap space. GC activity was reduced, running times were reduced (although still 3-4 times slower in comparison with the other languages). 

The execution time is a function of the available memory. And if we would remove .view, we would be comparing streaming APIs of 3 languages against Scala's strict, standard collections.

**Comment by dbcfd** [comment]
1. Can you try more new gen friendly vm settings? AdaptiveSizePolicy, set new gen size, try g0 parallel garbage collection.
2. Have you tried longer warmup times for jmh? Is your code being executed enough times in warmup for optimizations to kick in?

**Comment by DarkDimius** [comment]
FYI: -XX:+UseCondCardMark makes a difference in many parallel JVM setups, but not 4 times so picture will stay more-or-less the same.
also AFAIK LinqOptimizer does fusion in all cases, potentially changing the semantics, ScalaBlitz has fusion in development, but as our goal is to fuse only when it's safe to fuse, it's neither enabled by default nor publicly released.
Thanks for comparison, I'll use your codebase for other languages as a baseline for comparison.

**Comment by palladin** [comment]
Hi Dmitry,
LinqOptimizer performs loop fusion, nested loop generation and lambda inlining only when we can detect that it's safe (without changing LINQ's semantics). Our work is based on Microsoft's Research Steno Project http://www.msr-waypoint.com/pubs/173946/paper-pldi.pdf.

**Comment by DarkDimius** [comment]
Hi @palladin ,
yes, but AFAIK semantics for LINQ and ScalaCollections are different. LINQ doesn't encourage side-effecting operations and is non-strict, while we want ScalaBlitz work for all types of operations on ScalaCollections, maintaining order of observable effects.

**Comment by palladin** [comment]
It was an answer to "LinqOptimizer does fusion in all cases, potentially changing the semantics", I was talking about LINQ's semantics. LinqOptimizer does not break existing LINQ code.

**Comment by palladin** [comment]
From our discussion in this thread I can conclude that strict collections is the wrong default for functional pipelines. Not only adds GC pressure (intermediate temporary collections) but also adds additional complexity to optimizers like ScalaBlitz.

**Comment by axel22** [comment]
I think you should be dropping the `view` call. The parallel views are an almost deprecated feature that nobody is using any more, so one should really just use `par`, as Dmitry suggests.

**Comment by yanniss** [comment]
Hi @axel22 . These are excellent suggestions. They are already included in the numbers @biboudis posted as screenshots above. On Tuesday we will try to integrate these new measurements in the paper. It will probably be a separate subsection or an extra bar in the plots, since getting these (much improved yet still 3x-4x slower than other languages) numbers requires 4x the heap size for Scala and the use of an abstraction that we do not consider semantically equivalent.

**Comment by Ichoran** [comment]
Starting with an Array of primitives and using generic collections operations is pretty much the worst thing you can do for performance in Scala.  The interface with generic collections is made for convenience, not performance.  In particular, the values are stored as primitives, then must be boxed going into the method call, where they must be unboxed and operated on, then boxed again, and then, if it's going back into an array, unboxed...so that it can get boxed again on the next operation!  That's a lot of extra work for the JVM to try to figure out how to skip.

For instance, if you use a List instead of an Array--where the numbers are stored boxed--your times should go down by about a factor of two because you skip the extra boxing step.  (I'm also unconvinced that you've warmed up enough to see what the JVM can really do with optimization.)  For a lazy version, a view on a Vector should improve things some (non-parallel).

**Comment by biboudis** [comment]
A new benchmark is added based on this PR. Thanks.

**Pull request closed without merging**
